apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-alert
  namespace: bnctl-dolphinscheduler-uat-ns
  labels:
    app.kubernetes.io/component: alert
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster-alert
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-code-sync-pvc
  namespace: bnctl-dolphinscheduler-uat-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem

